language: csharp
script:
  - echo "Information(Context.Environment.Runtime.CakeVersion.ToString());" > build.cake
  - ./build.sh || exit 1
  - echo "Testing with modules/addin packages.config"
  - mkdir tools/modules
  - echo -e "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<packages>\r\n    <package id=\"Cake.Paket.Module\" version=\"1.2.2\" />\r\n</packages>" > ./tools/modules/packages.config
  - mkdir tools/addins
  - echo -e "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<packages>\r\n    <package id=\"Cake.MicrosoftTeams\" version=\"0.3.0\" />\r\n</packages>" > ./tools/addins/packages.config
  - ./build.sh || exit 1
  - ls -D -R
os:
  - linux